clear;
mitd=sortrows(importdata('mitd'));
qgld=sortrows(importdata('qgld'));
qglf=sortrows(importdata('qglf'));
qtxd=sortrows(importdata('qtxd'));
qtxf=sortrows(importdata('qtxf'));
qcsd=sortrows(importdata('qcsd'));
qcsf=sortrows(importdata('qcsf'));
energy = mitd(:,1);
difqgld=abs(mitd-qgld);
difqglf=abs(mitd-qglf);
difqtxd=abs(mitd-qtxd);
difqtxf=abs(mitd-qtxf);
difqcsd=abs(mitd-qcsd);
difqcsf=abs(mitd-qcsf);
figure;loglog(energy,difqgld);
difqgld=abs(mitd(:,2:4)-qgld(:,2:4));
figure;loglog(energy,difqgld);
legend('total','abs','fission');
title('quickw double');